import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MiniKitProvider from "@/app/_components/minikit-provider";
import dynamic from "next/dynamic";
import NextAuthProvider from "@/app/_components/next-auth-provider";
import Nav from "@/app/_components/Nav";
import "@worldcoin/mini-apps-ui-kit-react/styles.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const ErudaProvider = dynamic(
    () => import("./_components/Eruda").then((c) => c.ErudaProvider),
    {
      ssr: false,
    }
  );
  return (
    <html lang="en" className="">
      <body className={inter.className + ""}>
        <div className="h-full w-full overflow-y-auto">
          <NextAuthProvider>
            <ErudaProvider>
              <MiniKitProvider>
                <Nav />
                {children}
              </MiniKitProvider>
            </ErudaProvider>
          </NextAuthProvider>
        </div>
      </body>
    </html>
  );
}
